/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedUploadRouteRouteImport } from './routes/_protected.upload/route'
import { Route as PublicIndexRouteRouteImport } from './routes/_public.index/route'
import { Route as PublicComponentsRouteRouteImport } from './routes/_public.components/route'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUploadRouteRoute = ProtectedUploadRouteRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicIndexRouteRoute = PublicIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicComponentsRouteRoute = PublicComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRouteRoute
  '/upload': typeof ProtectedUploadRouteRoute
  '/components': typeof PublicComponentsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRouteRoute
  '/upload': typeof ProtectedUploadRouteRoute
  '/components': typeof PublicComponentsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/': typeof PublicIndexRouteRoute
  '/_protected/upload': typeof ProtectedUploadRouteRoute
  '/_public/components': typeof PublicComponentsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upload' | '/components'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upload' | '/components'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/'
    | '/_protected/upload'
    | '/_public/components'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/upload': {
      id: '/_protected/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof ProtectedUploadRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/components': {
      id: '/_public/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof PublicComponentsRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedUploadRouteRoute: typeof ProtectedUploadRouteRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedUploadRouteRoute: ProtectedUploadRouteRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRouteRoute: typeof PublicIndexRouteRoute
  PublicComponentsRouteRoute: typeof PublicComponentsRouteRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRouteRoute: PublicIndexRouteRoute,
  PublicComponentsRouteRoute: PublicComponentsRouteRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
